/*

  config-win32.h is generated by autoconf from config-win32.h.in
  This file is for internal use only.  It should not be #included in
  programs.

  This file should include things that would normally go into a
  config.h if we could use autoconf and config.h.in in Windows.  Note
  that you need autoconf to generate config-win32.h from
  config-win32.h.in, so if you're in Windows, put things in
  config-win32.h if you have to and move them into config-win32.h.in
  before submitting a patch.  You may need to generate config-win32.h
  from hand.

 */

#define GNET_MAJOR_VERSION 1
#define GNET_MINOR_VERSION 0
#define GNET_MICRO_VERSION 3
#define GNET_INTERFACE_AGE 3
#define GNET_BINARY_AGE    3
