CC = gcc
FLAGS = -g -Wall -mno-cygwin -mpentium -fnative-struct -DGNET_EXPERIMENTAL=1
LINK =  -lgnet-1.1 -lglib-1.3 -lws2_32
INC = -I../glib -I. -I../gnet -L../glib -L../gnet
all:
	$(CC) $(FLAGS) $(INC) echoserver.c -o echoserver $(LINK)
	$(CC) $(FLAGS) $(INC) echoclient.c -o echoclient $(LINK)
	$(CC) $(FLAGS) $(INC) echoserver-udp.c -o udp-server $(LINK)
	$(CC) $(FLAGS) $(INC) echoclient-udp.c -o udp-client $(LINK)
	$(CC) $(FLAGS) $(INC) hfetch.c -o hfetch $(LINK)